const musicLibrary = [
    {
        title: 'Then You Can Tell Me Goodbye',
        artist: 'Bettye Swan',
        genre: 'Soul',
        rating: 5,
        url: 'https://images-na.ssl-images-amazon.com/images/I/41pfL83uu3L._SX355_.jpg',
        id: 1,
    },
    {
        title: 'These Arms Of Mine',
        artist: 'Otis Redding',
        genre: 'Soul',
        rating: 5,
        url: 'https://m.media-amazon.com/images/I/61ssPmUElxL._SS500_.jpg',
        id: 2,
    },
    {
        title: 'Wish You Were Here',
        artist: 'Pink Floyd',
        genre: 'Rock',
        rating: 4,
        url: 'https://m.media-amazon.com/images/I/71nar1rZYIL._SS500_.jpg',
        id: 3,
    },
    {
        title: 'Heroes',
        artist: 'David Bowie',
        genre: 'Pop',
        rating: 4,
        url: 'https://images-na.ssl-images-amazon.com/images/I/81VycvvC49L._AC_SL1300_.jpg',
        id: 4,
    },
    {
        title: 'Paint It Black',
        artist: 'The Rolling Stones',
        genre: 'Rock',
        rating: 4,
        url: 'https://images-na.ssl-images-amazon.com/images/I/61IpwmL5gJL._AC_SY355_.jpg',
        id: 5,
    },
    {
        title: 'Jolene',
        artist: 'Dolly Parton',
        genre: 'Country',
        rating: 4,
        url: 'https://m.media-amazon.com/images/I/71mvq7YMbCL._SS500_.jpg',
        id: 6,
    },
    {
        title: 'God Only Knows',
        artist: 'The Beach Boys',
        genre: 'Pop',
        rating: 5,
        url: 'https://images-eu.ssl-images-amazon.com/images/I/61QbDQO6cdL.__AC_SX300_SY300_QL70_ML2_.jpg',
        id: 7,
    },
    {
        title: 'Zeg Me Dat Het Niet Zo Is',
        artist: 'Frank Boeijen Groep',
        genre: 'Nederlandstalig',
        rating: 4,
        url: 'https://images.45cat.com/frank-boeijen-groep-zeg-me-dat-het-niet-zo-is-ariola-s.jpg',
        id: 8,
    },
    {
        title: 'Your Song',
        artist: 'Elton John',
        genre: 'Pop',
        rating: 3,
        url: 'https://m.media-amazon.com/images/I/6181zytNa5L._SS500_.jpg',
        id: 9,
    },
    {
        title: 'Don\'t Look Back In Anger',
        artist: 'Oasis',
        genre: 'Rock',
        rating: 2,
        url: 'https://m.media-amazon.com/images/I/81ZXwflZa2L._SS500_.jpg',
        id: 10,
    },
    {
        title: 'Whole Lotta Love',
        artist: 'Led Zeppelin',
        genre: 'Rock',
        rating: 4,
        url: 'https://media.hitparade.ch/cover/big/led_zeppelin-whole_lotta_love_s.jpg',
        id: 11,
    },
    {
        title: 'The End',
        artist: 'The Doors',
        genre: 'Rock',
        rating: 3,
        url: 'https://img.discogs.com/pktFIKgF0mFmZ5yoRHJ91aj9cno=/fit-in/381x398/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-3114696-1316454617.jpeg.jpg',
        id: 12,
    },
    {
        title: 'Born Slippy',
        artist: 'Underworld',
        genre: 'Dance',
        rating: 4,
        url: 'https://lastfm.freetls.fastly.net/i/u/770x0/39ec47154e755d8f0972cea462c3c803.jpg',
        id: 13,
    },
    {
        title: 'Love Will Tear Us Apart',
        artist: 'Joy Division',
        genre: 'New Wave',
        rating: 3,
        url: 'https://images-na.ssl-images-amazon.com/images/I/71clPUzpU4L._AC_SX355_.jpg',
        id: 14,
    },
    {
        title: 'De Vondeling Van Ameland',
        artist: 'Boudewijn de Groot',
        genre: 'Nederlandstalig',
        rating: 5,
        url: 'https://img.discogs.com/EKFwuLNZ0s1qfiDGlIaeRboY1fo=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/R-15011347-1585483032-6791.jpeg.jpg',
        id: 15,
    },
    {
        title: 'Blowin\' In The Wind',
        artist: 'Bob Dylan',
        genre: 'Folk',
        rating: 5,
        url: 'https://images-na.ssl-images-amazon.com/images/I/81XczPXeIjL._SL1200_.jpg',
        id: 16,
    },
    {
        title: 'Friday I\'m In Love',
        artist: 'The Cure',
        genre: 'New Wave',
        rating: 2,
        url: 'https://images-na.ssl-images-amazon.com/images/I/81lm34tRPIL._SL1380_.jpg',
        id: 17,
    },
    {
        title: '9 Crimes',
        artist: 'Damien Rice',
        genre: 'Pop',
        rating: 4,
        url: 'https://media.hitparade.ch/cover/big/damien_rice-9_crimes_s_1.jpg',
        id: 18,
    },
    {
        title: 'Fool On The Hill',
        artist: 'The Beatles',
        genre: 'Pop',
        rating: 5,
        url: 'https://jabuinwords.files.wordpress.com/2016/05/fool-on-the-hill.jpg',
        id: 19,
    },
    {
        title: 'You\'re So Vain',
        artist: 'Carly Simon',
        genre: 'Folk',
        rating: 4,
        url: 'https://media.hitparade.ch/cover/big/carly_simon-youre_so_vain_s.jpg',
        id: 20,
    },
    {
        title: 'At Last',
        artist: 'Etta James',
        genre: 'Soul',
        rating: 4,
        url: 'https://www.udiscovermusic.com/wp-content/uploads/2018/08/Etta-James-At-Last-album.jpg',
        id: 21,
    },
    {
        title: 'Love Is A Losing Game',
        artist: 'Amy Winehouse',
        genre: 'Pop',
        rating: 2,
        url: 'https://media.hitparade.ch/cover/big/amy_winehouse-love_is_a_losing_game_s.jpg',
        id: 22,
    },
    {
        title: 'Niggas In Paris',
        artist: 'Jay Z & Kanye West',
        genre: 'Hip Hop',
        rating: 4,
        url: 'https://i1.sndcdn.com/artworks-000127059350-d55bk6-t500x500.jpg',
        id: 23,
    },
    {
        title: 'Let\'s Stay Together',
        artist: 'Al Green',
        genre: 'Soul',
        rating: 4,
        url: 'https://images-na.ssl-images-amazon.com/images/I/81wFC4WzGvL._AC_SY355_.jpg',
        id: 24,
    },
    {
        title: 'Georgia On My Mind',
        artist: 'Ray Charles',
        genre: 'Soul',
        rating: 3,
        url: 'https://img.discogs.com/B_2aY5EK21hqOsLVb4MItVZAM9o=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/R-11141323-1510606107-5434.jpeg.jpg',
        id: 25,
    },
    {
        title: 'Ol\'55',
        artist: 'Tom Waits',
        genre: 'Folk',
        rating: 4,
        url: 'https://images.genius.com/77b98d63aa8e9b4a14db816e45a58d18.1000x1000x1.png',
        id: 26,
    },
    {
        title: 'Sunday Morning Comin\' Down',
        artist: 'Kris Kristofferson',
        genre: 'Folk',
        rating: 2,
        url: 'https://img.discogs.com/jzKAwxzbSm9wI_hKcau8ZAKSSYM=/fit-in/500x500/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1771127-1242292841.jpeg.jpg',
        id: 27,
    },
    {
        title: 'Stars',
        artist: 'Janis Ian',
        genre: 'Pop',
        rating: 3,
        url: 'https://img.discogs.com/WO4JC2zeND55AIDKFIQvtwo9QqA=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-564280-1290059357.jpeg.jpg',
        id: 28,
    },
    {
        title: 'The First Cut Is The Deepest',
        artist: 'Cat Stevens',
        genre: 'Folk',
        rating: 4,
        url: 'https://img.discogs.com/5kJTJd-aygy1yE2c-djNJFsQFGc=/fit-in/600x598/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-7490489-1442561264-4313.jpeg.jpg',
        id: 29,
    },
    {
        title: 'Dream A Little Dream Of Me',
        artist: 'Mama Cass',
        genre: 'Folk',
        rating: 5,
        url: 'https://images.45worlds.com/s/ab/mama-cass-dream-a-little-dream-ab-s.jpg',
        id: 30,
    },
    {
        title: 'You Don\'t Have To Say You Love Me',
        artist: 'Dusty Springfield',
        genre: 'Pop',
        rating: 4,
        url: 'https://upload.wikimedia.org/wikipedia/en/7/77/You_Don%27t_Have_to_Say_You_Love_Me.jpg',
        id: 31,
    },
    {
        title: 'Call Me',
        artist: 'St. Paul & The Broken Bones',
        genre: 'Soul',
        rating: 4,
        url: 'https://img.discogs.com/BCaBGxgxzAuxfuOW4ptjrMdRITY=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/R-5899503-1405803124-4549.jpeg.jpg',
        id: 32,
    },
    {
        title: '100 Days, 100 Nights',
        artist: 'Sharon Jones & The Dap-Kings',
        genre: 'Soul',
        rating: 4,
        url: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/25/Sharon-Jones-100-days.jpg/220px-Sharon-Jones-100-days.jpg',
        id: 33,
    },
    {
        title: 'L$D',
        artist: 'A$AP Rocky',
        genre: 'Hip Hop',
        rating: 4,
        url: 'https://images.genius.com/36f22176265617232d365a6ffbd331c7.800x800x1.png',
        id: 34,
    },
    {
        title: 'Sky And Sand',
        artist: 'Paul & Fritz Kalkbrenner',
        genre: 'Dance',
        rating: 3,
        url: 'https://upload.wikimedia.org/wikipedia/en/c/c0/Sky_and_Sand.jpg',
        id: 35,
    },
];

export default musicLibrary;